// data.js

const units = {
    unit1: [
        { word: "individual", hint: "An object described in a set of data. Can be people, animals, or things." },
        { word: "categorical variable", hint: "A variable that places each individual into a particular group, called a category." },
        { word: "quantitative variable", hint: "A variable that takes number values that are quantities—counts or measurements." },
        { word: "discrete variable", hint: "A quantitative variable that takes a fixed set of possible values with gaps between them." },
        { word: "continuous variable", hint: "A quantitative variable that can take any value in an interval on the number line." },
        { word: "distribution", hint: "Of a variable, tells us what values the variable takes and how often it takes those values." },
        { word: "frequency table", hint: "Table that shows the number of individuals having each value." },
        { word: "relative frequency table", hint: "Table that shows the proportion or percent of individuals having each value." },
        { word: "bar graph", hint: "Graph that shows each category as a bar. The heights of the bars show the category frequencies or relative frequencies." },
        { word: "pie chart", hint: "Chart that shows each category as a slice of pie. The areas of the slices are proportional to the category frequencies or relative frequencies." },
        { word: "two way table", hint: "A table of counts that summarizes data on the relationship between two categorical variables for some group of individuals." },
        { word: "marginal relative frequency", hint: "Gives the percent or proportion of individuals that have a specific value for one categorical variable." },
        { word: "joint relative frequency", hint: "Gives the percent or proportion of individuals that have a specific value for one categorical variable and a specific value for another categorical variable." },
        { word: "conditional relative frequency", hint: "Gives the percent or proportion of individuals that have a specific value for one categorical variable among individuals who share the same value of another categorical variable." },
        { word: "side by side bar graph", hint: "Graph that displays the distribution of a categorical variable for each value of another categorical variable. The bars are grouped together based on the values of one of the categorical variables and placed side by side." },
        { word: "segmented bar graph", hint: "Graph that displays the distribution of a categorical variable as segments of a rectangle, with the area of each segment proportional to the percent of individuals in the corresponding category." },
        { word: "mosaic plot", hint: "A modified segmented bar graph in which the width of each rectangle is proportional to the number of individuals in the corresponding category." },
        { word: "association", hint: "A relationship between variables thats lets the value of one variable help predict the value of another variable." },
        { word: "dotplot", hint: "Shows each data value as a dot above its location on a number line." },
        { word: "symmetric distribution", hint: "A distribution where the right side of the graph (containing the half of observations with the largest values) is approximately a mirror image of the left side." },
        { word: "right skewed distribution", hint: "A distribution where the right side of the graph is much longer and flatter than the left side." },
        { word: "left skewed distribution", hint: "A distribution where the left side of the graph is much longer and flatter than the right side." },
        { word: "stemplot", hint: "Plot that shows each data value separated into two parts: a stem, which consists of all but the final digit, and a leaf, the final digit." },
        { word: "histogram", hint: "Shows each interval of values as a bar. The heights of the bars show the frequencies or relative frequencies of values in each interval." },
        { word: "mean", hint: "The average of all the individual data values in a dataset." },
        { word: "statistic", hint: "A number that describes some characteristic of a sample." },
        { word: "parameter", hint: "A number that describes some characteristic of a population." },
        { word: "resistant", hint: "Used to describe a statistical measure that isn't sensitive to outliers" },
        { word: "median", hint: "The midpoint of a distribution, the number such that about half the observations are smaller and about half are larger." },
        { word: "range", hint: "The distance between the minimum value and the maximum value." },
        { word: "standard deviation", hint: "Measures the typical distance of the values in a distribution from the mean." },
        { word: "variance", hint: "The average squared deviation." },
        { word: "quartiles", hint: "The quartiles of a distribution divide the ordered data set into four groups having roughly the same number of values." },
        { word: "interquartile range", hint: "The distance between the first and third quartiles of a distribution." },
        { word: "five number summary", hint: "Consists of the minimum, the first quartile Q1, the median, the third quartile Q3, and the maximum." },
        { word: "boxplot", hint: "A visual representation of the five-number summary." },
        { word: "density curve", hint: "Models the distribution of a quantitative variable with a curve that: Is always on or above the horizontal axis; Has area exactly 1 underneath it." },
        { word: "normal distribution", hint: "A distribution that is described by a symmetric, single-peaked, bell-shaped density curve" },
        { word: "empirical rule", hint: "68%-95%-99.7% rule for standard deviations from the mean" },
        { word: "standard normal distribution", hint: "The Normal distribution with mean 0 and standard deviation 1." },
        { word: "percentile", hint: "The 𝘱th percentile of a distribution is the value with 𝘱% of observations less than or equal to it. " },
        { word: "cumulative relative frequency graph", hint: "Plots a point corresponding to the percentile of a given value in a distribution of quantitative data. Consecutive points are then connected with a line segment to form the graph. " },
        { word: "z-score", hint: "For an individual value in a distribution, tells us how many standard deviations from the mean the value falls, and in what direction. " },
    ],
    unit2: [
        { word: "response variable", hint: "A variable that measures an outcome of a study." },
        { word: "explanatory variable", hint: "A variable that may help predict or explain changes in a response variable." },
        { word: "scatterplot", hint: "Plot that shows the relationship between two quantitative variables measured on the same individuals." },
        { word: "positive association", hint: "A directly proportional relationship between two variables where one variable's increase causes an increase in the other." },
        { word: "negative association", hint: "An inversely proportional relationship between two variables where one's increase causes the other to decrease." },
        { word: "no association", hint: "No relationship between two variables: the values of one doesn't help explain or predict the values of another." },
        { word: "correlation", hint: "𝓇: Measures the direction and strength of the association between two quantitative variables." },
        { word: "regression line", hint: "A line that models how a response variable y changes as an explanatory variable x changes." },
        { word: "extrapolation", hint: "The use of a regression line for prediction outside the interval of x values used to obtain the line." },
        { word: "residual", hint: "The difference between the actual value of y and the value of y, predicted by the regression line." },
        { word: "y-intercept", hint: "a: The predicted value of y when x = 0." },
        { word: "slope", hint: "b: The amount by which the predicted value of y changes when x increases by 1 unit." },
        { word: "least squares regression line", hint: "The line that makes the sum of the squared residuals as small as possible." },
        { word: "residual plot", hint: "A scatterplot that displays the residuals on the vertical axis and the explanatory variable on the horizontal axis." },
        { word: "standard deviation of the residuals", hint: "s: Measures the typical distance between the actual y values and the predicted y values." },
        { word: "coefficient of determination", hint: "r²: Measures the percent of the variability in the response variable that is accounted for by the least-squares regression line." },
        { word: "outlier", hint: "A point that does not follow the pattern of the data and has a large residual." },
        { word: "influential point", hint: "A point that, if removed, substantially changes the slope, y intercept, correlation, coefficient of determination, or standard deviation of the residuals." },
    ],
    unit3: [
        { word: "population", hint: "The entire group of individuals that we want information about in a study." },
        { word: "census", hint: "Data collection from every individual in a population." },
        { word: "sample", hint: "A subset of the population from which data is collected." },
        { word: "sample survey", hint: "Collects data from a sample to learn about the larger population." },
        { word: "convenience sampling", hint: "Sampling individuals who are easiest to reach." },
        { word: "bias", hint: "When a study design systematically underestimates or overestimates the true value." },
        { word: "voluntary response sampling", hint: "Sampling where participants choose to respond to a general invitation." },
        { word: "random sampling", hint: "A method of sampling where a chance process is used to select members from the population." },
        { word: "simple random sample", hint: "A sample where every group of n individuals has an equal chance of being selected." },
        { word: "sampling without replacement", hint: "A sample where each individual can only be selected once." },
        { word: "sampling with replacement", hint: "A sample where individuals can be selected more than once." },
        { word: "strata", hint: "Groups in a population that share characteristics related to the variables being studied." },
        { word: "stratified random sampling", hint: "Choosing a sample by selecting an SRS from each stratum." },
        { word: "cluster", hint: "A group of individuals located near each other." },
        { word: "cluster sampling", hint: "Randomly choosing clusters and including all members in the sample." },
        { word: "systematic random sampling", hint: "Selecting every kth individual from an ordered population after randomly picking the first one." },
        { word: "undercoverage", hint: "When some members of the population are less likely or unable to be selected." },
        { word: "nonresponse", hint: "Occurs when selected individuals can't be contacted or refuse to participate." },
        { word: "response bias", hint: "A pattern of inaccurate answers to a survey question." },
        { word: "observational study", hint: "Observes individuals and measures variables without influencing them." },
        { word: "response variable", hint: "The outcome being measured in a study." },
        { word: "explanatory variable", hint: "A variable that may help predict or explain changes in the response variable." },
        { word: "confounding variable", hint: "When there is another variable that can affect the explanatory variable's effect on the response variable." },
        { word: "experiment", hint: "A study where treatments are imposed to observe their effects." },
        { word: "placebo", hint: "A treatment with no active ingredient, used as a control." },
        { word: "treatment", hint: "A specific condition applied in an experiment." },
        { word: "experimental unit", hint: "The object that receives a treatment." },
        { word: "subjects", hint: "Human participants in an experiment." },
        { word: "factor", hint: "An explanatory variable that is manipulated in an experiment." },
        { word: "levels", hint: "The different values of a factor in an experiment." },
        { word: "control group", hint: "A group used as a baseline for comparison, which may receive no treatment or a placebo." },
        { word: "placebo", hint: "When subjects respond to a treatment that has no active ingredient." },
        { word: "double blind", hint: "Neither subjects nor experimenters know who receives the treatment." },
        { word: "single- ", hint: "Either the subjects or the experimenters don't know who receives the treatment." },
        { word: "random assignment", hint: "Assigning treatments to experimental units using a chance process." },
        { word: "control", hint: "Keeping other variables constant across all experimental units." },
        { word: "replication", hint: "Applying each treatment to enough experimental units to distinguish differences from chance." },
        { word: "block", hint: "A group of similar experimental units that are treated separately." },
        { word: "randomized block design", hint: "Random assignment within each block of similar experimental units." },
        { word: "matched pairs design", hint: "Pairs of similar units are assigned different treatments, or the same unit receives both treatments in random order." },
        { word: "sampling variability", hint: "The fact that different random samples of the same size produce different estimates." },
        { word: "statistically significant", hint: "When study results are unlikely to occur by chance alone." }
    ],
    unit4: [
        { word: "random process", hint: "A process that generates outcomes determined purely by chance." },
        { word: "probability", hint: "A number between 0 and 1 that describes how often an outcome occurs in many trials." },
        { word: "law of large numbers", hint: "A law that states as more trials are observed, the proportion of times a specific outcome occurs approaches its probability." },
        { word: "simulation", hint: "Imitates a random process to produce outcomes consistent with real-world results." },
        { word: "probability model", hint: "A model that describes a random process with a list of outcomes and their probabilities." },
        { word: "sample space", hint: "The list of all possible outcomes in a process." },
        { word: "event", hint: "Any collection of outcomes from a random process." },
        { word: "complement rule", hint: "A rule where the probability of an event not occurring is 1 minus the probability of it occurring." },
        { word: "mutually exclusive", hint: "Two events that cannot occur together." },
        { word: "intersection", hint: "The outcomes common to both events A and B." },
        { word: "union", hint: "The outcomes in event A, event B, or both." },
        { word: "conditional probability", hint: "The probability of an event given that another event has occurred." },
        { word: "independent events", hint: "Events where knowing one does not affect the probability of the other." },
        { word: "tree diagram", hint: "A diagram that shows the sample space of a process involving multiple stages, with probabilities on each branch." },
        { word: "random variable", hint: "Takes numerical values that describe the outcomes of a process." },
        { word: "binomial distribution", hint: "The distribution of the number of successes for n independent trials in a binomial setting." },
        { word: "10% condition", hint: "A condition that states in a random sample of size n from a population of size N, n must be less than 10% of N for individual observations to be treated as independent." },
        { word: "large counts condition", hint: "A condition that states a binomial distribution is approximately normal if the expected counts of successes and failures are both at least 10." },
        { word: "geometric distribution", hint: "The distribution of the number of trials it takes to get a success in a geometric setting." },
    ],
    unit5: [
        { word: "sampling distribution", hint: "The distribution of values for a statistic across all possible samples of the same size from a population." },
        { word: "unbiased estimator", hint: "Can be used as the parameter if the sampling distribution's mean equals the parameter being estimated." },
        { word: "sample proportion", hint: "ρ̂  (p-hat): Ratio of number of successes in a sample to the size of the sample." },
        { word: "sample mean", hint: "x: Average of a sample." },
        { word: "central limit theorem (clt)", hint: "In a sufficiently large SRS (n ≥ 30), the sampling distribution of the sample mean is approximately Normal, regardless of population distribution." },
    ],
    unit6: [
        { word: "point estimator", hint: "A statistic that estimates a population parameter." },
        { word: "point estimate", hint: "The specific value of a point estimator from a sample." },
        { word: "confidence interval", hint: "An interval of plausible values for a parameter, calculated as point estimate ± margin of error." },
        { word: "confidence level", hint: "The success rate of the method used to calculate the confidence interval, often expressed as C%." },
        { word: "margin of error", hint: "How far we expect the estimate to vary from the true value in C% of all samples." },
        { word: "critical value", hint: "The multiplier that determines the width of a confidence interval based on the confidence level and sampling distribution." },
        { word: "standard error", hint: "An estimate of how far the statistic typically varies from the parameter it's estimating." },
        { word: "significance test", hint: "A formal procedure to decide between two competing claims about a parameter using observed data." },
        { word: "null hypothesis", hint: "H₀: The claim we test evidence against, often a statement of no difference." },
        { word: "alternative hypothesis", hint: "Hₐ: The claim we seek evidence for in a significance test." },
        { word: "one-sided alternative hypothesis", hint: "An alternative hypothesis that states a parameter is either greater or less than the null value." },
        { word: "two-sided alternative hypothesis", hint: "An alternative hypothesis that states a parameter is different from the null value." },
        { word: "p-value", hint: "The probability of observing evidence as strong as the actual data, assuming the null hypothesis is true." },
        { word: "significance level", hint: "α: A fixed value used as a boundary to decide if a result is too unlikely under the null hypothesis." },
        { word: "type 1 error", hint: "Rejecting the null hypothesis when it is actually true." },
        { word: "type 2 error", hint: "Failing to reject the null hypothesis when the alternative hypothesis is true." },
        { word: "t-score", hint: "Measures how far a sample statistic is from what we expect if the null hypothesis is true, in standard deviation units." },
        { word: "power", hint: "The probability that a test will detect convincing evidence for the alternative hypothesis when it is true." },
    ],
    unit7: [
        { word: "two-sample z interval", hint: "Confidence interval to estimate the difference in proportions between two populations or treatments." },
        { word: "combined sample proportion", hint: "The overall proportion of successes in two combined samples." },
        { word: "two-sample z test", hint: "Test of whether the proportions of successes in two populations are equal." },
        { word: "two-sample t interval", hint: "Confidence interval to estimate the difference in means between two populations or treatments." },
        { word: "two-sample t test", hint: "Test of whether the means of two populations are equal." },
        { word: "paired data", hint: "Data where two values of the same variable recorded for each individual or pair of similar individuals." },
        { word: "paired t interval", hint: "Confidence interval to estimate the mean difference in paired data." },
        { word: "one-sample t interval", hint: "Confidence interval to estimate a population mean." },
        { word: "paired t test", hint: "Test of whether the mean difference in paired data equals a specified value, often 0." },
    ],
    unit8: [
        { word: "one way table", hint: "A table showing the distribution of a single categorical variable." },
        { word: "observed counts", hint: "The actual number of individuals in each cell of a table." },
        { word: "expected counts", hint: "The number of individuals expected in each cell if the null hypothesis is true." },
        { word: "chi-square", hint: "χ²: Measures how far observed counts are from expected counts, using the formula." },
        { word: "chi-square distribution", hint: "A distribution that is skewed right and takes non-negative values, defined by degrees of freedom." },
        { word: "chi-square test for goodness of fit", hint: "Tests whether a categorical variable follows a specified distribution." },
        { word: "chi-square test for homogeneity", hint: "Tests whether the distribution of a categorical variable is the same across multiple populations or treatments." },
        { word: "chi-square test for independence", hint: "Tests whether there is an association between two categorical variables." },
        { word: "population regression line", hint: "The regression line based on the entire population." },
        { word: "sample regression line", hint: "The least-squares regression line ŷ = b₀ + b₁x computed from sample data." },
        { word: "t-interval for slope", hint: "A confidence interval used to estimate the slope of a population regression line." },
        { word: "t-test for slope", hint: "A test of whether there is no linear relationship between two quantitative variables." },
    ]
};